//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box_Master
    {
        public int Box_Id { get; set; }
        public Nullable<int> Box_No { get; set; }
        public string Status { get; set; }
        public string State { get; set; }
        public Nullable<int> Store_Id { get; set; }
    }
}
