//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Inventory
    {
        public int Id { get; set; }
        public string Game_Id { get; set; }
        public string Packet_Id { get; set; }
        public string Lottery_Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
    }
}
