//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee_Details
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int StoreId { get; set; }
        public string EmailId { get; set; }
        public string EmailId1 { get; set; }
        public string EmailId2 { get; set; }
        public string Store_Address { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<bool> IsAssignStore { get; set; }
        public string Contact { get; set; }
        public Nullable<bool> IsRememberMe { get; set; }
    }
}
