//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLottery_Inventory
    {
        public int Master_ListID { get; set; }
        public string GameID { get; set; }
        public string TicketName { get; set; }
        public Nullable<int> Price { get; set; }
        public string Start_No { get; set; }
        public string End_No { get; set; }
        public string Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string State { get; set; }
        public Nullable<int> Store_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
    }
}
