//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReturnticket
    {
        public int Returnticket_Id { get; set; }
        public string Game_Id { get; set; }
        public string Packet_Id { get; set; }
        public Nullable<int> Box_No { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Modified_On { get; set; }
        public string Ticket_Name { get; set; }
        public string Price { get; set; }
        public string PackPosition_Open { get; set; }
        public string PackPosition_Close { get; set; }
        public string Return_At { get; set; }
        public string State { get; set; }
        public Nullable<int> EmplyeeeId { get; set; }
        public Nullable<int> Count { get; set; }
        public int Store_Id { get; set; }
        public Nullable<int> ShiftID { get; set; }
    }
}
