//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSoldOut_History
    {
        public int Id { get; set; }
        public string Packet_Id { get; set; }
        public Nullable<System.DateTime> SoldOut_Date { get; set; }
        public Nullable<int> No_of_Tickets_Sold { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> Shift_Id { get; set; }
    }
}
