//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStore_Info
    {
        public int Store_Id { get; set; }
        public string Store_Name { get; set; }
        public string Open_Time { get; set; }
        public string Close_Time { get; set; }
        public Nullable<int> No_Of_Boxes { get; set; }
        public string EmailId1 { get; set; }
        public string EmailId2 { get; set; }
        public string EmailId3 { get; set; }
        public string Store_Address { get; set; }
        public Nullable<int> Settlement_Day { get; set; }
        public Nullable<bool> Auto_Settle { get; set; }
        public string Store_Status { get; set; }
        public Nullable<bool> Email1_On_Off { get; set; }
        public Nullable<bool> Email2_On_Off { get; set; }
        public Nullable<bool> Email3_On_Off { get; set; }

    }
}
