//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShift
    {
        public int ShiftID { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int ID { get; set; }
        public int StoreId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsLastShift { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<bool> IsReportGenerated { get; set; }
    }
}
