//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreEmployeeInfo
    {
        public int Id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Store_Address { get; set; }
        public string Employee_Address { get; set; }
    }
}
