//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerminal_Data1
    {
        public int TerminalData_Id1 { get; set; }
        public string Scratch_Payout { get; set; }
        public string Online_Sells { get; set; }
        public string Online_Payout { get; set; }
        public string Loan { get; set; }
        public string Cash_On_Hand { get; set; }
        public int Credit { get; set; }
        public int Debit { get; set; }
        public int Top_Up_Cancel { get; set; }
        public int Top_Up { get; set; }
        public Nullable<int> Store_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public string Issued_Inventory { get; set; }
        public string InStock_Inventory { get; set; }
        public string Active_Inventory { get; set; }
        public string Total { get; set; }
        public string Scratch_Sells { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CountRecevied { get; set; }
        public Nullable<int> CountActive { get; set; }
        public string Total_Stock_Inventory { get; set; }
        public string Total_Active_Inventory { get; set; }
        public string Net_Cash { get; set; }
    }
}
