//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string User_name { get; set; }
        public string U_Password { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Shop_id { get; set; }
        public string Shop_name { get; set; }
        public string State { get; set; }
        public string S_Code { get; set; }
    }
}
