//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotteryNewAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketMaster
    {
        public int Id { get; set; }
        public string Game_Id { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Modified_ON { get; set; }
        public string State { get; set; }
    }
}
